swagger: "2.0"
info:
  title: BackendDev swagger UI Docs
  description: BackendDev documentation made by Lahcene DERGHAM .
  version: 1.0
  contact:
    email: l.dergham@esi-sba.dz
  liscence:
    name: ME
  servers:
    -url: http://localhost:4000
    description: This is my local Server
schemes: [http]
